apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: torch
  namespace: torch
  labels: 
    app: torch
spec:
  selector:
    matchLabels:
      app: torch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: torch
    spec:
      nodeSelector:
        gpu: "true"
      containers:
      - image: registry.tonberry.org/tonberry/torch:1.0
        name: torch 
        env:
        ports:
        - containerPort: 8888 
          name: jupyter 
          #volumeMounts:
          #- name: torch-persistent-storage
          #mountPath: /var/torch/
          #volumes:
          #- name: torch-persistent-storage
          # persistentVolumeClaim:
          #claimName: torch-claim
